### ISSUE TITLE
Error in link

### ISSUE THREAD

**Issue by solomonbstoner** [radare/radare2book#100]
> For partial emulation (or imprecise full emulation) radare2 uses its own [ESIL](https://radare.gitbooks.io/radare2book/content/analysis/disassembling/esil.md) intermediate language and virtual machine.
>  
> --[Emulation](https://radare.gitbooks.io/radare2book/content/analysis/emulation.html)

The hyperlink in "ESIL" is wrong. I believe the intended URL is : https://radare.gitbooks.io/radare2book/content/disassembling/esil.html .

**Comment by radare** [comment]
Press the pencil button and do a pullreq instead of opening an issue

**Comment by solomonbstoner** [comment]
Created [pullreq](https://github.com/radare/radare2book/pull/101) as instructed.
