### ISSUE TITLE
Redo all screenshots with one color theme

### ISSUE THREAD

**Issue by XVilka** [radare/radare2book#104]
To be consistent across the whole book

**Comment by radare** [comment]
Just use the tool i wrote that takes a script and generates an image. FOR ALL THE CODE SNIPPETS. This is important for printing. Please someone with computer do that

**Comment by XVilka** [comment]
But you said that some snippets looks better as snippets?

**Comment by XVilka** [comment]
One more thing - I think we should preserve the original text for all snippets - because anyway in the online book text looking is better than the image. Not sure if we can make it conditional somehow.

**Comment by radare** [comment]
Only if they are small. But yep we should chek the pdf and see if theres any other wrong snippet

**Comment by radare** [comment]
Fixed
