### ISSUE TITLE
Better document visual panels mode

### ISSUE THREAD

**Issue by XVilka** [radare/radare2book#106]
Extract it from the visual mode chapter, extend it and make a new chapter.

**Comment by radare** [comment]
![screen shot 2018-07-17 at 13 19 19](https://user-images.githubusercontent.com/917142/42814281-0c31946e-89c4-11e8-9cce-e917d7a36df3.png)

add this section here

pls @Vane11ope

**Comment by Vane11ope** [comment]
okaaaaaay!!!

**Comment by ITAYC0HEN** [comment]
Done and merged: https://github.com/radare/radare2book/commit/a1110358806bb25485beae56867d19632ffd12ba

Good job!
