### ISSUE TITLE
Do not include "Architectures" section in the printable book

### ISSUE THREAD

**Issue by radare** [radare/radare2book#110]
only 8051? full of checkboxes for todos? wtf

![screen shot 2018-07-17 at 12 53 33](https://user-images.githubusercontent.com/917142/42813240-95fe8516-89c0-11e8-81c7-68d35add3a2a.png)

**Comment by Maijin** [comment]
We probably want to include the r2 comparison page instead but we should build a script that create that

**Comment by XVilka** [comment]
To be honest I am not sure it is needed in the printed version at all. I would skip this one for printing.

**Comment by radare** [comment]
imho all sections should have more than 1 subsection, otherwise it looks really poor

**Comment by XVilka** [comment]
Yes, but what I mean it is not required for a printed book
