### ISSUE TITLE
anal.bb.split is gone

### ISSUE THREAD

**Issue by mrmacete** [radare/radare2book#117]
but it's referenced here: https://github.com/radare/radare2book/blob/master/analysis/code_analysis.md

**Comment by radare** [comment]
press the pencil button and do the pr from the website, takes less time than filling issues :P

**Comment by mrmacete** [comment]
yeah just don't know if there's a new way to do that

**Comment by radare** [comment]
nope, this variable is deprecated, theres nothing to configure here, basic blocks are always splitted in the analysis loop
