### ISSUE TITLE
Win32 not setting register values

### ISSUE THREAD

**Issue by jorgeventura** [radare/radare2book#207]
I have radare2 compiled using MS Visual C 2019 and the compilation complete with no problem for radare2 version 3.5.1.

The problem I am having is that any assignment for register (dr eax=0x01) doesn't work.

I did checkout for version 3.5.0 and I am recompiling to see if it fixes the problem.

By the way, I tried to recompile the last commit but in this case I have an error at compilation.

**Comment by radare** [comment]
Which error? Master builds fine in appveyour

**Comment by jorgeventura** [comment]
Hi,
I am recompiling the master to get the error.
The result of version 3.5.0 was OK and the "dr <reg>=<val>" is working fine.

**Comment by jorgeventura** [comment]
This is the error when I compile the master.
I can keep the machine running to test for you if that helps. Just send me patches or if you commit I can pull and retry.

>       "c:\Users\sysadmin\radare2\build\radare2.sln" (default target) (1) ->
>       "c:\Users\sysadmin\radare2\build\libr\core\f105261@@r_core@sha.vcxproj" (default target) (42) ->
>       (ClCompile target) ->
>         c:\Users\sysadmin\radare2\libr\core\windows_heap.c(549): error C2065: '_M_X64': undeclared identifier [c:\Users\sysadmin\radare2\build\libr\core\f105261@@r_core@sha.vcxproj]
> 
>    398 Warning(s)
>    1 Error(s)
>

**Comment by radare** [comment]
i pushed a fix for thjis, that was clearly wrong

**Comment by jorgeventura** [comment]
I am going to test and give you a return.

Thank you.

**Comment by jorgeventura** [comment]
Hi,
I recompiled the last version with no error what is good but the issue
about change register value persists and I am using the old commit that
everything is fine for both platforms. If you fix the issue about register
for Win32 I can test for you.

Sincerely,
Ventura

At linux
radare2 3.5.0-git 21719 @ linux-x86-64 git.3.4.1-409-g7d158e443
commit: 7d158e443b0ac7370bac732f74378b5bf23fd583 build: 2019-05-14__18:54:49

At Windows Win32
radare2 3.5.0-git 22061 @ windows-x86-32 git.3.4.1-409-g7d158e443
commit: 7d158e443b0ac7370bac732f74378b5bf23fd583 build: Wed
06/12/2019__15:31.46.84

**Comment by radare** [comment]
So in which commit was fine?

**Comment by jorgeventura** [comment]
7d158e443b0ac7370bac732f74378b5bf23fd583
