### ISSUE TITLE
Positioning related to ELF files 

### ISSUE THREAD

**Issue by benquike** [radare/radare2book#22]
When radare2 opens an ELF file, where does it set its starting position to?

when we use seek command to move the current position back and force,  does it move in the virtual address space of the ELF file? or does it move in the offset from the beginning of the ELF file?

Please clarify this

**Comment by radare** [comment]
> On 30 Mar 2016, at 16:16, Hui Peng <notifications@github.com> wrote:
> 
> When radare2 opens an ELF file, where does it set its starting position to?
> 
> 
entrypoint
> when we use seek command to move the current position back and force, does it move in the virtual address space of the ELF file? or does it move in the offset from the beginning of the ELF file?
> 

unless you use -n, r2 will work in va mode

**Comment by benquike** [comment]
@radare Thanks

**Comment by Maijin** [comment]
If you can add a pull request in the book where you think this info should be added, otherwise, I'll do it myself later.
