### ISSUE TITLE
Widnows compilation section out of date

### ISSUE THREAD

**Issue by pandasauce** [radare/radare2book#39]
```/introduction/windows_compilation.md```

Following the guide will result in runtime dependency on libgcc.

```sys/mingw32.bat``` seems to be up to date, however paths are hardcoded and it won't work out of the box as the book suggests.

MinGW-w64 build by the book fails with error on ```shlr/zip/zip/zip_close.c:645``` complaining about ```_O_BINARY```, so something is missing from that part too.

**Comment by XVilka** [comment]
@pandasauce thx, I'll address those, by updating r2 scripts instead of book - that's the proper way.

**Comment by pandasauce** [comment]
Update on the zip issue: not an actual issue; I forgot to switch from msys2 shell to mingw32 shell after installing zip, it compiles fine on mingw32 shell.

Differences between shells on MSYS2: https://sourceforge.net/p/msys2/wiki/MSYS2%20introduction/

**Comment by XVilka** [comment]
I think this can be closed now, no? Should be fixed.
