### ISSUE TITLE
Overview mentions rasm2 support for MSIL

### ISSUE THREAD

**Issue by pawlos** [radare/radare2book#59]
In the [overview](https://radare.gitbooks.io/radare2book/content/introduction/overview.html) section it is mentioned that `rasm2` supports MSIL. If it is then this architecture should be renamed to [CIL](https://en.wikipedia.org/wiki/Common_Intermediate_Language) as the MSIL is a deprecated name but running `rasm2 -L` does not list that architecture.

MSIL is also mentioned in `rasm2` [intro](https://radare.gitbooks.io/radare2book/content/rasm2/intro.html).

Was MSIL removed and the book is not updated in that part?

**Comment by radare** [comment]
This change should be done in radare2-extras too because the msil support is no longer in core

**Comment by pawlos** [comment]
@radare where it is? I can correct those places and make PR.

**Comment by radare** [comment]
https://github.com/radare/radare2-extras/tree/master/libr/asm/arch/msil <https://github.com/radare/radare2-extras/tree/master/libr/asm/arch/msil>

https://github.com/radare/radare2-extras/issues/126 <https://github.com/radare/radare2-extras/issues/126>

..
