### ISSUE TITLE
Add 'dd' operation description and usage example

### ISSUE THREAD

**Issue by XVilka** [radare/radare2book#8]

**Comment by radare** [comment]
this is explained in `dd?` what else do you need?

**Comment by XVilka** [comment]
Examples? I don't need that. Users need that.

**Comment by Maijin** [comment]
@XVilka dd is easy to use, but mentioning it existence wouldn't kill

**Comment by radare** [comment]
ok ^^ didnt realized this was not the radare2 repo :D

**Comment by radare** [comment]
I dont have a computer right now to show examples. But i put a description and that may be good at least as an introduction. Feel free to add examples and demos if you have a computer
